INSERT INTO Book (title, author, numCopies, category) VALUES ("Mom's Family Wall Calendar 2016", "Sandra Boynton", 3, "Calendars");
INSERT INTO Book (title, author, numCopies, category) VALUES ("Doug the Pug 2016 Wall Calendar", "Doug the Pug", 3, "Calendars");
INSERT INTO Book (title, author, numCopies, category) VALUES ("Moleskine 2016 Weekly Notebook, 12M, Large, Black, Soft Cover (5 x 8.25)", "Moleskine", 3, "Calendars");
INSERT INTO Book (title, author, numCopies, category) VALUES ("365 Cats Color Page-A-Day Calendar 2016", "Workman Publishing", 3, "Calendars");
INSERT INTO Book (title, author, numCopies, category) VALUES ("Sierra Club Engagement Calendar 2016", "Sierra Club", 3, "Calendars");
INSERT INTO Book (title, author, numCopies, category) VALUES ("Sierra Club Wilderness Calendar 2016", "Sierra Club", 3, "Calendars");
INSERT INTO Book (title, author, numCopies, category) VALUES ("Thomas Kinkade: The Disney Dreams Collection 2016 Wall Calendar", "Thomas Kinkade", 3, "Calendars");
INSERT INTO Book (title, author, numCopies, category) VALUES ("Ansel Adams 2016 Wall Calendar", "", 3, "Calendars");
INSERT INTO Book (title, author, numCopies, category) VALUES ("Dilbert 2016 Day-to-Day Calendar", "Scott Adams", 3, "Calendars");
INSERT INTO Book (title, author, numCopies, category) VALUES ("Mary Engelbreit 2016 Deluxe Wall Calendar: Never Give Up", "Mary Engelbreit", 3, "Calendars");
INSERT INTO Book (title, author, numCopies, category) VALUES ("Cat Page-A-Day Gallery Calendar 2016", "Workman Publishing", 3, "Calendars");
INSERT INTO Book (title, author, numCopies, category) VALUES ("Llewellyn's 2016 Witches' Datebook", "Jane Meredith", 3, "Calendars");
INSERT INTO Book (title, author, numCopies, category) VALUES ("2016 Amy Knapp Big Grid Wall Calendar: The essential organization and communication tool for the entire family", "Amy Knapp", 3, "Calendars");
INSERT INTO Book (title, author, numCopies, category) VALUES ("Outlander 2016 Wall Calendar", "Starz", 3, "Calendars");
INSERT INTO Book (title, author, numCopies, category) VALUES ("Audubon Nature Wall Calendar 2016", "National Audubon Society", 3, "Calendars");
INSERT INTO Book (title, author, numCopies, category) VALUES ("2016 National Park Foundation Wall Calendar", "National Parks Foundation", 3, "Calendars");
INSERT INTO Book (title, author, numCopies, category) VALUES ("Color Your Year Wall Calendar 2016: Mindful Coloring Through the Seasons", "Workman Publishing", 3, "Calendars");
INSERT INTO Book (title, author, numCopies, category) VALUES ("Mary Engelbreit 2016 Day-to-Day Calendar: Enjoy the Joy", "Mary Engelbreit", 3, "Calendars");
INSERT INTO Book (title, author, numCopies, category) VALUES ("Grumpy Cat 2016 Wall Calendar", "Grumpy Cat", 3, "Calendars");
INSERT INTO Book (title, author, numCopies, category) VALUES ("Moleskine 2016 Weekly Notebook, 12M, Extra Large, Black, Soft Cover (7.5 x 10)", "Moleskine", 3, "Calendars");
INSERT INTO Book (title, author, numCopies, category) VALUES ("Llewellyn's 2016 Witches' Calendar", "Barbara Ardinger", 3, "Calendars");
INSERT INTO Book (title, author, numCopies, category) VALUES ("Moleskine 2016 Weekly Notebook, 12M, Pocket, Black, Soft Cover (3.5 x 5.5)", "Moleskine", 3, "Calendars");
INSERT INTO Book (title, author, numCopies, category) VALUES ("2016 Susan Branch Wall Calendar", "Susan Branch", 3, "Calendars");
INSERT INTO Book (title, author, numCopies, category) VALUES ("365 Dogs Color Page-A-Day Calendar 2016", "Workman Publishing", 3, "Calendars");
INSERT INTO Book (title, author, numCopies, category) VALUES ("Dog Page-A-Day Gallery Calendar 2016", "Workman Publishing", 3, "Calendars");
INSERT INTO Book (title, author, numCopies, category) VALUES ("MAXINE  Year-In-A-Box Calendar (2016)", "Year-In-A-Box", 3, "Calendars");
INSERT INTO Book (title, author, numCopies, category) VALUES ("Disney Descendants Wall Calendar (2016)", "Day Dream", 3, "Calendars");
INSERT INTO Book (title, author, numCopies, category) VALUES ("Walking Dead 2016 Wall Calendar", "Amc", 3, "Calendars");
INSERT INTO Book (title, author, numCopies, category) VALUES ("The Complete Runner's Day-by-Day Log 2016 Calendar", "Marty Jerome", 3, "Calendars");
INSERT INTO Book (title, author, numCopies, category) VALUES ("Llewellyn's 2016 Astrological Calendar: 83rd Edition of the World's Best Known, Most Trusted Astrology Calendar", "Llewellyn", 3, "Calendars");
INSERT INTO Book (title, author, numCopies, category) VALUES ("Today Is Going to Be a Great Day! Color Page-A-Day Calendar 2016", "Workman Publishing", 3, "Calendars");
INSERT INTO Book (title, author, numCopies, category) VALUES ("French Country Diary 2016 Calendar", "Linda Dannenberg", 3, "Calendars");
INSERT INTO Book (title, author, numCopies, category) VALUES ("Pusheen the Cat 2016 Wall Calendar", "Claire Belton", 3, "Calendars");
INSERT INTO Book (title, author, numCopies, category) VALUES ("Posh: Coloring 2016 Day-to-Day Calendar: For Fun & Relaxation", "Thaneeya McArdle", 3, "Calendars");
INSERT INTO Book (title, author, numCopies, category) VALUES ("Posh: Coloring 2015-2016 Large Monthly/Weekly Planning Calendar", "Andrews McMeel Publishing LLC", 3, "Calendars");
INSERT INTO Book (title, author, numCopies, category) VALUES ("Moleskine 2016 Monthly Notebook, 12M, Extra Large, Black, Soft Cover (7.5 x 10)", "Moleskine", 3, "Calendars");
INSERT INTO Book (title, author, numCopies, category) VALUES ("Mary Engelbreit 2016 Weekly Planner Calendar: Smile! It's Good For  You", "Mary Engelbreit", 3, "Calendars");
INSERT INTO Book (title, author, numCopies, category) VALUES ("The Old Farmer's Almanac 2016 Gardening Calendar", "Old FarmerE€Es Almanac", 3, "Calendars");
INSERT INTO Book (title, author, numCopies, category) VALUES ("Mary Engelbreit 2016 Monthly Pocket Planner: Just Being ME!", "Mary Engelbreit", 3, "Calendars");
INSERT INTO Book (title, author, numCopies, category) VALUES ("2016 Someecards Daily Desktop Calendar", "Someecards", 3, "Calendars");
