INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (1, 1, "Mom's Family Wall Calendar 2016", "Sandra Boynton", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (1, 2, "Mom's Family Wall Calendar 2016", "Sandra Boynton", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (1, 3, "Mom's Family Wall Calendar 2016", "Sandra Boynton", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (2, 1, "Doug the Pug 2016 Wall Calendar", "Doug the Pug", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (2, 2, "Doug the Pug 2016 Wall Calendar", "Doug the Pug", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (2, 3, "Doug the Pug 2016 Wall Calendar", "Doug the Pug", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (3, 1, "Moleskine 2016 Weekly Notebook, 12M, Large, Black, Soft Cover (5 x 8.25)", "Moleskine", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (3, 2, "Moleskine 2016 Weekly Notebook, 12M, Large, Black, Soft Cover (5 x 8.25)", "Moleskine", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (3, 3, "Moleskine 2016 Weekly Notebook, 12M, Large, Black, Soft Cover (5 x 8.25)", "Moleskine", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (4, 1, "365 Cats Color Page-A-Day Calendar 2016", "Workman Publishing", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (4, 2, "365 Cats Color Page-A-Day Calendar 2016", "Workman Publishing", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (4, 3, "365 Cats Color Page-A-Day Calendar 2016", "Workman Publishing", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (5, 1, "Sierra Club Engagement Calendar 2016", "Sierra Club", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (5, 2, "Sierra Club Engagement Calendar 2016", "Sierra Club", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (5, 3, "Sierra Club Engagement Calendar 2016", "Sierra Club", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (6, 1, "Sierra Club Wilderness Calendar 2016", "Sierra Club", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (6, 2, "Sierra Club Wilderness Calendar 2016", "Sierra Club", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (6, 3, "Sierra Club Wilderness Calendar 2016", "Sierra Club", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (7, 1, "Thomas Kinkade: The Disney Dreams Collection 2016 Wall Calendar", "Thomas Kinkade", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (7, 2, "Thomas Kinkade: The Disney Dreams Collection 2016 Wall Calendar", "Thomas Kinkade", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (7, 3, "Thomas Kinkade: The Disney Dreams Collection 2016 Wall Calendar", "Thomas Kinkade", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (8, 1, "Ansel Adams 2016 Wall Calendar", "", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (8, 2, "Ansel Adams 2016 Wall Calendar", "", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (8, 3, "Ansel Adams 2016 Wall Calendar", "", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (9, 1, "Dilbert 2016 Day-to-Day Calendar", "Scott Adams", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (9, 2, "Dilbert 2016 Day-to-Day Calendar", "Scott Adams", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (9, 3, "Dilbert 2016 Day-to-Day Calendar", "Scott Adams", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (10, 1, "Mary Engelbreit 2016 Deluxe Wall Calendar: Never Give Up", "Mary Engelbreit", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (10, 2, "Mary Engelbreit 2016 Deluxe Wall Calendar: Never Give Up", "Mary Engelbreit", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (10, 3, "Mary Engelbreit 2016 Deluxe Wall Calendar: Never Give Up", "Mary Engelbreit", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (11, 1, "Cat Page-A-Day Gallery Calendar 2016", "Workman Publishing", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (11, 2, "Cat Page-A-Day Gallery Calendar 2016", "Workman Publishing", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (11, 3, "Cat Page-A-Day Gallery Calendar 2016", "Workman Publishing", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (12, 1, "Llewellyn's 2016 Witches' Datebook", "Jane Meredith", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (12, 2, "Llewellyn's 2016 Witches' Datebook", "Jane Meredith", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (12, 3, "Llewellyn's 2016 Witches' Datebook", "Jane Meredith", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (13, 1, "2016 Amy Knapp Big Grid Wall Calendar: The essential organization and communication tool for the entire family", "Amy Knapp", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (13, 2, "2016 Amy Knapp Big Grid Wall Calendar: The essential organization and communication tool for the entire family", "Amy Knapp", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (13, 3, "2016 Amy Knapp Big Grid Wall Calendar: The essential organization and communication tool for the entire family", "Amy Knapp", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (14, 1, "Outlander 2016 Wall Calendar", "Starz", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (14, 2, "Outlander 2016 Wall Calendar", "Starz", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (14, 3, "Outlander 2016 Wall Calendar", "Starz", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (15, 1, "Audubon Nature Wall Calendar 2016", "National Audubon Society", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (15, 2, "Audubon Nature Wall Calendar 2016", "National Audubon Society", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (15, 3, "Audubon Nature Wall Calendar 2016", "National Audubon Society", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (16, 1, "2016 National Park Foundation Wall Calendar", "National Parks Foundation", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (16, 2, "2016 National Park Foundation Wall Calendar", "National Parks Foundation", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (16, 3, "2016 National Park Foundation Wall Calendar", "National Parks Foundation", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (17, 1, "Color Your Year Wall Calendar 2016: Mindful Coloring Through the Seasons", "Workman Publishing", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (17, 2, "Color Your Year Wall Calendar 2016: Mindful Coloring Through the Seasons", "Workman Publishing", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (17, 3, "Color Your Year Wall Calendar 2016: Mindful Coloring Through the Seasons", "Workman Publishing", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (18, 1, "Mary Engelbreit 2016 Day-to-Day Calendar: Enjoy the Joy", "Mary Engelbreit", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (18, 2, "Mary Engelbreit 2016 Day-to-Day Calendar: Enjoy the Joy", "Mary Engelbreit", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (18, 3, "Mary Engelbreit 2016 Day-to-Day Calendar: Enjoy the Joy", "Mary Engelbreit", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (19, 1, "Grumpy Cat 2016 Wall Calendar", "Grumpy Cat", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (19, 2, "Grumpy Cat 2016 Wall Calendar", "Grumpy Cat", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (19, 3, "Grumpy Cat 2016 Wall Calendar", "Grumpy Cat", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (20, 1, "Moleskine 2016 Weekly Notebook, 12M, Extra Large, Black, Soft Cover (7.5 x 10)", "Moleskine", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (20, 2, "Moleskine 2016 Weekly Notebook, 12M, Extra Large, Black, Soft Cover (7.5 x 10)", "Moleskine", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (20, 3, "Moleskine 2016 Weekly Notebook, 12M, Extra Large, Black, Soft Cover (7.5 x 10)", "Moleskine", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (21, 1, "Llewellyn's 2016 Witches' Calendar", "Barbara Ardinger", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (21, 2, "Llewellyn's 2016 Witches' Calendar", "Barbara Ardinger", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (21, 3, "Llewellyn's 2016 Witches' Calendar", "Barbara Ardinger", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (22, 1, "Moleskine 2016 Weekly Notebook, 12M, Pocket, Black, Soft Cover (3.5 x 5.5)", "Moleskine", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (22, 2, "Moleskine 2016 Weekly Notebook, 12M, Pocket, Black, Soft Cover (3.5 x 5.5)", "Moleskine", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (22, 3, "Moleskine 2016 Weekly Notebook, 12M, Pocket, Black, Soft Cover (3.5 x 5.5)", "Moleskine", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (23, 1, "2016 Susan Branch Wall Calendar", "Susan Branch", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (23, 2, "2016 Susan Branch Wall Calendar", "Susan Branch", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (23, 3, "2016 Susan Branch Wall Calendar", "Susan Branch", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (24, 1, "365 Dogs Color Page-A-Day Calendar 2016", "Workman Publishing", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (24, 2, "365 Dogs Color Page-A-Day Calendar 2016", "Workman Publishing", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (24, 3, "365 Dogs Color Page-A-Day Calendar 2016", "Workman Publishing", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (25, 1, "Dog Page-A-Day Gallery Calendar 2016", "Workman Publishing", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (25, 2, "Dog Page-A-Day Gallery Calendar 2016", "Workman Publishing", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (25, 3, "Dog Page-A-Day Gallery Calendar 2016", "Workman Publishing", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (26, 1, "MAXINE  Year-In-A-Box Calendar (2016)", "Year-In-A-Box", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (26, 2, "MAXINE  Year-In-A-Box Calendar (2016)", "Year-In-A-Box", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (26, 3, "MAXINE  Year-In-A-Box Calendar (2016)", "Year-In-A-Box", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (27, 1, "Disney Descendants Wall Calendar (2016)", "Day Dream", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (27, 2, "Disney Descendants Wall Calendar (2016)", "Day Dream", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (27, 3, "Disney Descendants Wall Calendar (2016)", "Day Dream", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (28, 1, "Walking Dead 2016 Wall Calendar", "Amc", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (28, 2, "Walking Dead 2016 Wall Calendar", "Amc", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (28, 3, "Walking Dead 2016 Wall Calendar", "Amc", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (29, 1, "The Complete Runner's Day-by-Day Log 2016 Calendar", "Marty Jerome", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (29, 2, "The Complete Runner's Day-by-Day Log 2016 Calendar", "Marty Jerome", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (29, 3, "The Complete Runner's Day-by-Day Log 2016 Calendar", "Marty Jerome", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (30, 1, "Llewellyn's 2016 Astrological Calendar: 83rd Edition of the World's Best Known, Most Trusted Astrology Calendar", "Llewellyn", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (30, 2, "Llewellyn's 2016 Astrological Calendar: 83rd Edition of the World's Best Known, Most Trusted Astrology Calendar", "Llewellyn", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (30, 3, "Llewellyn's 2016 Astrological Calendar: 83rd Edition of the World's Best Known, Most Trusted Astrology Calendar", "Llewellyn", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (31, 1, "Today Is Going to Be a Great Day! Color Page-A-Day Calendar 2016", "Workman Publishing", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (31, 2, "Today Is Going to Be a Great Day! Color Page-A-Day Calendar 2016", "Workman Publishing", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (31, 3, "Today Is Going to Be a Great Day! Color Page-A-Day Calendar 2016", "Workman Publishing", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (32, 1, "French Country Diary 2016 Calendar", "Linda Dannenberg", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (32, 2, "French Country Diary 2016 Calendar", "Linda Dannenberg", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (32, 3, "French Country Diary 2016 Calendar", "Linda Dannenberg", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (33, 1, "Pusheen the Cat 2016 Wall Calendar", "Claire Belton", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (33, 2, "Pusheen the Cat 2016 Wall Calendar", "Claire Belton", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (33, 3, "Pusheen the Cat 2016 Wall Calendar", "Claire Belton", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (34, 1, "Posh: Coloring 2016 Day-to-Day Calendar: For Fun & Relaxation", "Thaneeya McArdle", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (34, 2, "Posh: Coloring 2016 Day-to-Day Calendar: For Fun & Relaxation", "Thaneeya McArdle", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (34, 3, "Posh: Coloring 2016 Day-to-Day Calendar: For Fun & Relaxation", "Thaneeya McArdle", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (35, 1, "Posh: Coloring 2015-2016 Large Monthly/Weekly Planning Calendar", "Andrews McMeel Publishing LLC", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (35, 2, "Posh: Coloring 2015-2016 Large Monthly/Weekly Planning Calendar", "Andrews McMeel Publishing LLC", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (35, 3, "Posh: Coloring 2015-2016 Large Monthly/Weekly Planning Calendar", "Andrews McMeel Publishing LLC", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (36, 1, "Moleskine 2016 Monthly Notebook, 12M, Extra Large, Black, Soft Cover (7.5 x 10)", "Moleskine", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (36, 2, "Moleskine 2016 Monthly Notebook, 12M, Extra Large, Black, Soft Cover (7.5 x 10)", "Moleskine", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (36, 3, "Moleskine 2016 Monthly Notebook, 12M, Extra Large, Black, Soft Cover (7.5 x 10)", "Moleskine", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (37, 1, "Mary Engelbreit 2016 Weekly Planner Calendar: Smile! It's Good For  You", "Mary Engelbreit", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (37, 2, "Mary Engelbreit 2016 Weekly Planner Calendar: Smile! It's Good For  You", "Mary Engelbreit", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (37, 3, "Mary Engelbreit 2016 Weekly Planner Calendar: Smile! It's Good For  You", "Mary Engelbreit", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (38, 1, "The Old Farmer's Almanac 2016 Gardening Calendar", "Old FarmerE€Es Almanac", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (38, 2, "The Old Farmer's Almanac 2016 Gardening Calendar", "Old FarmerE€Es Almanac", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (38, 3, "The Old Farmer's Almanac 2016 Gardening Calendar", "Old FarmerE€Es Almanac", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (39, 1, "Mary Engelbreit 2016 Monthly Pocket Planner: Just Being ME!", "Mary Engelbreit", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (39, 2, "Mary Engelbreit 2016 Monthly Pocket Planner: Just Being ME!", "Mary Engelbreit", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (39, 3, "Mary Engelbreit 2016 Monthly Pocket Planner: Just Being ME!", "Mary Engelbreit", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (40, 1, "2016 Someecards Daily Desktop Calendar", "Someecards", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (40, 2, "2016 Someecards Daily Desktop Calendar", "Someecards", 3, "Calendars");
INSERT INTO Book (id, copyNum, title, author, numCopies, category) VALUES (40, 3, "2016 Someecards Daily Desktop Calendar", "Someecards", 3, "Calendars");
