# Right now there are only 40 out of 200,000 books included in here. 

INSERT INTO Book (id, copyNum, title, author, category) VALUES (1, 1, "Mom's Family Wall Calendar 2016", "Sandra Boynton", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (1, 2, "Mom's Family Wall Calendar 2016", "Sandra Boynton", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (1, 3, "Mom's Family Wall Calendar 2016", "Sandra Boynton", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (2, 1, "Doug the Pug 2016 Wall Calendar", "Doug the Pug", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (2, 2, "Doug the Pug 2016 Wall Calendar", "Doug the Pug", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (2, 3, "Doug the Pug 2016 Wall Calendar", "Doug the Pug", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (3, 1, "Moleskine 2016 Weekly Notebook, 12M, Large, Black, Soft Cover (5 x 8.25)", "Moleskine", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (3, 2, "Moleskine 2016 Weekly Notebook, 12M, Large, Black, Soft Cover (5 x 8.25)", "Moleskine", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (3, 3, "Moleskine 2016 Weekly Notebook, 12M, Large, Black, Soft Cover (5 x 8.25)", "Moleskine", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (4, 1, "365 Cats Color Page-A-Day Calendar 2016", "Workman Publishing", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (4, 2, "365 Cats Color Page-A-Day Calendar 2016", "Workman Publishing", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (4, 3, "365 Cats Color Page-A-Day Calendar 2016", "Workman Publishing", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (5, 1, "Sierra Club Engagement Calendar 2016", "Sierra Club", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (5, 2, "Sierra Club Engagement Calendar 2016", "Sierra Club", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (5, 3, "Sierra Club Engagement Calendar 2016", "Sierra Club", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (6, 1, "Sierra Club Wilderness Calendar 2016", "Sierra Club", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (6, 2, "Sierra Club Wilderness Calendar 2016", "Sierra Club", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (6, 3, "Sierra Club Wilderness Calendar 2016", "Sierra Club", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (7, 1, "Thomas Kinkade: The Disney Dreams Collection 2016 Wall Calendar", "Thomas Kinkade", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (7, 2, "Thomas Kinkade: The Disney Dreams Collection 2016 Wall Calendar", "Thomas Kinkade", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (7, 3, "Thomas Kinkade: The Disney Dreams Collection 2016 Wall Calendar", "Thomas Kinkade", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (8, 1, "Ansel Adams 2016 Wall Calendar", "", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (8, 2, "Ansel Adams 2016 Wall Calendar", "", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (8, 3, "Ansel Adams 2016 Wall Calendar", "", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (9, 1, "Dilbert 2016 Day-to-Day Calendar", "Scott Adams", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (9, 2, "Dilbert 2016 Day-to-Day Calendar", "Scott Adams", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (9, 3, "Dilbert 2016 Day-to-Day Calendar", "Scott Adams", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (10, 1, "Mary Engelbreit 2016 Deluxe Wall Calendar: Never Give Up", "Mary Engelbreit", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (10, 2, "Mary Engelbreit 2016 Deluxe Wall Calendar: Never Give Up", "Mary Engelbreit", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (10, 3, "Mary Engelbreit 2016 Deluxe Wall Calendar: Never Give Up", "Mary Engelbreit", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (11, 1, "Cat Page-A-Day Gallery Calendar 2016", "Workman Publishing", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (11, 2, "Cat Page-A-Day Gallery Calendar 2016", "Workman Publishing", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (11, 3, "Cat Page-A-Day Gallery Calendar 2016", "Workman Publishing", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (12, 1, "Llewellyn's 2016 Witches' Datebook", "Jane Meredith", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (12, 2, "Llewellyn's 2016 Witches' Datebook", "Jane Meredith", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (12, 3, "Llewellyn's 2016 Witches' Datebook", "Jane Meredith", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (13, 1, "2016 Amy Knapp Big Grid Wall Calendar: The essential organization and communication tool for the entire family", "Amy Knapp", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (13, 2, "2016 Amy Knapp Big Grid Wall Calendar: The essential organization and communication tool for the entire family", "Amy Knapp", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (13, 3, "2016 Amy Knapp Big Grid Wall Calendar: The essential organization and communication tool for the entire family", "Amy Knapp", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (14, 1, "Outlander 2016 Wall Calendar", "Starz", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (14, 2, "Outlander 2016 Wall Calendar", "Starz", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (14, 3, "Outlander 2016 Wall Calendar", "Starz", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (15, 1, "Audubon Nature Wall Calendar 2016", "National Audubon Society", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (15, 2, "Audubon Nature Wall Calendar 2016", "National Audubon Society", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (15, 3, "Audubon Nature Wall Calendar 2016", "National Audubon Society", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (16, 1, "2016 National Park Foundation Wall Calendar", "National Parks Foundation", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (16, 2, "2016 National Park Foundation Wall Calendar", "National Parks Foundation", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (16, 3, "2016 National Park Foundation Wall Calendar", "National Parks Foundation", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (17, 1, "Color Your Year Wall Calendar 2016: Mindful Coloring Through the Seasons", "Workman Publishing", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (17, 2, "Color Your Year Wall Calendar 2016: Mindful Coloring Through the Seasons", "Workman Publishing", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (17, 3, "Color Your Year Wall Calendar 2016: Mindful Coloring Through the Seasons", "Workman Publishing", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (18, 1, "Mary Engelbreit 2016 Day-to-Day Calendar: Enjoy the Joy", "Mary Engelbreit", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (18, 2, "Mary Engelbreit 2016 Day-to-Day Calendar: Enjoy the Joy", "Mary Engelbreit", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (18, 3, "Mary Engelbreit 2016 Day-to-Day Calendar: Enjoy the Joy", "Mary Engelbreit", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (19, 1, "Grumpy Cat 2016 Wall Calendar", "Grumpy Cat", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (19, 2, "Grumpy Cat 2016 Wall Calendar", "Grumpy Cat", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (19, 3, "Grumpy Cat 2016 Wall Calendar", "Grumpy Cat", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (20, 1, "Moleskine 2016 Weekly Notebook, 12M, Extra Large, Black, Soft Cover (7.5 x 10)", "Moleskine", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (20, 2, "Moleskine 2016 Weekly Notebook, 12M, Extra Large, Black, Soft Cover (7.5 x 10)", "Moleskine", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (20, 3, "Moleskine 2016 Weekly Notebook, 12M, Extra Large, Black, Soft Cover (7.5 x 10)", "Moleskine", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (21, 1, "Llewellyn's 2016 Witches' Calendar", "Barbara Ardinger", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (21, 2, "Llewellyn's 2016 Witches' Calendar", "Barbara Ardinger", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (21, 3, "Llewellyn's 2016 Witches' Calendar", "Barbara Ardinger", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (22, 1, "Moleskine 2016 Weekly Notebook, 12M, Pocket, Black, Soft Cover (3.5 x 5.5)", "Moleskine", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (22, 2, "Moleskine 2016 Weekly Notebook, 12M, Pocket, Black, Soft Cover (3.5 x 5.5)", "Moleskine", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (22, 3, "Moleskine 2016 Weekly Notebook, 12M, Pocket, Black, Soft Cover (3.5 x 5.5)", "Moleskine", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (23, 1, "2016 Susan Branch Wall Calendar", "Susan Branch", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (23, 2, "2016 Susan Branch Wall Calendar", "Susan Branch", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (23, 3, "2016 Susan Branch Wall Calendar", "Susan Branch", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (24, 1, "365 Dogs Color Page-A-Day Calendar 2016", "Workman Publishing", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (24, 2, "365 Dogs Color Page-A-Day Calendar 2016", "Workman Publishing", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (24, 3, "365 Dogs Color Page-A-Day Calendar 2016", "Workman Publishing", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (25, 1, "Dog Page-A-Day Gallery Calendar 2016", "Workman Publishing", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (25, 2, "Dog Page-A-Day Gallery Calendar 2016", "Workman Publishing", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (25, 3, "Dog Page-A-Day Gallery Calendar 2016", "Workman Publishing", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (26, 1, "MAXINE  Year-In-A-Box Calendar (2016)", "Year-In-A-Box", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (26, 2, "MAXINE  Year-In-A-Box Calendar (2016)", "Year-In-A-Box", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (26, 3, "MAXINE  Year-In-A-Box Calendar (2016)", "Year-In-A-Box", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (27, 1, "Disney Descendants Wall Calendar (2016)", "Day Dream", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (27, 2, "Disney Descendants Wall Calendar (2016)", "Day Dream", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (27, 3, "Disney Descendants Wall Calendar (2016)", "Day Dream", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (28, 1, "Walking Dead 2016 Wall Calendar", "Amc", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (28, 2, "Walking Dead 2016 Wall Calendar", "Amc", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (28, 3, "Walking Dead 2016 Wall Calendar", "Amc", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (29, 1, "The Complete Runner's Day-by-Day Log 2016 Calendar", "Marty Jerome", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (29, 2, "The Complete Runner's Day-by-Day Log 2016 Calendar", "Marty Jerome", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (29, 3, "The Complete Runner's Day-by-Day Log 2016 Calendar", "Marty Jerome", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (30, 1, "Llewellyn's 2016 Astrological Calendar: 83rd Edition of the World's Best Known, Most Trusted Astrology Calendar", "Llewellyn", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (30, 2, "Llewellyn's 2016 Astrological Calendar: 83rd Edition of the World's Best Known, Most Trusted Astrology Calendar", "Llewellyn", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (30, 3, "Llewellyn's 2016 Astrological Calendar: 83rd Edition of the World's Best Known, Most Trusted Astrology Calendar", "Llewellyn", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (31, 1, "Today Is Going to Be a Great Day! Color Page-A-Day Calendar 2016", "Workman Publishing", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (31, 2, "Today Is Going to Be a Great Day! Color Page-A-Day Calendar 2016", "Workman Publishing", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (31, 3, "Today Is Going to Be a Great Day! Color Page-A-Day Calendar 2016", "Workman Publishing", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (32, 1, "French Country Diary 2016 Calendar", "Linda Dannenberg", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (32, 2, "French Country Diary 2016 Calendar", "Linda Dannenberg", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (32, 3, "French Country Diary 2016 Calendar", "Linda Dannenberg", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (33, 1, "Pusheen the Cat 2016 Wall Calendar", "Claire Belton", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (33, 2, "Pusheen the Cat 2016 Wall Calendar", "Claire Belton", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (33, 3, "Pusheen the Cat 2016 Wall Calendar", "Claire Belton", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (34, 1, "Posh: Coloring 2016 Day-to-Day Calendar: For Fun & Relaxation", "Thaneeya McArdle", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (34, 2, "Posh: Coloring 2016 Day-to-Day Calendar: For Fun & Relaxation", "Thaneeya McArdle", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (34, 3, "Posh: Coloring 2016 Day-to-Day Calendar: For Fun & Relaxation", "Thaneeya McArdle", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (35, 1, "Posh: Coloring 2015-2016 Large Monthly/Weekly Planning Calendar", "Andrews McMeel Publishing LLC", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (35, 2, "Posh: Coloring 2015-2016 Large Monthly/Weekly Planning Calendar", "Andrews McMeel Publishing LLC", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (35, 3, "Posh: Coloring 2015-2016 Large Monthly/Weekly Planning Calendar", "Andrews McMeel Publishing LLC", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (36, 1, "Moleskine 2016 Monthly Notebook, 12M, Extra Large, Black, Soft Cover (7.5 x 10)", "Moleskine", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (36, 2, "Moleskine 2016 Monthly Notebook, 12M, Extra Large, Black, Soft Cover (7.5 x 10)", "Moleskine", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (36, 3, "Moleskine 2016 Monthly Notebook, 12M, Extra Large, Black, Soft Cover (7.5 x 10)", "Moleskine", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (37, 1, "Mary Engelbreit 2016 Weekly Planner Calendar: Smile! It's Good For  You", "Mary Engelbreit", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (37, 2, "Mary Engelbreit 2016 Weekly Planner Calendar: Smile! It's Good For  You", "Mary Engelbreit", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (37, 3, "Mary Engelbreit 2016 Weekly Planner Calendar: Smile! It's Good For  You", "Mary Engelbreit", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (38, 1, "The Old Farmer's Almanac 2016 Gardening Calendar", "Old FarmerE€Es Almanac", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (38, 2, "The Old Farmer's Almanac 2016 Gardening Calendar", "Old FarmerE€Es Almanac", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (38, 3, "The Old Farmer's Almanac 2016 Gardening Calendar", "Old FarmerE€Es Almanac", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (39, 1, "Mary Engelbreit 2016 Monthly Pocket Planner: Just Being ME!", "Mary Engelbreit", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (39, 2, "Mary Engelbreit 2016 Monthly Pocket Planner: Just Being ME!", "Mary Engelbreit", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (39, 3, "Mary Engelbreit 2016 Monthly Pocket Planner: Just Being ME!", "Mary Engelbreit", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (40, 1, "2016 Someecards Daily Desktop Calendar", "Someecards", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (40, 2, "2016 Someecards Daily Desktop Calendar", "Someecards", "Calendars");
INSERT INTO Book (id, copyNum, title, author, category) VALUES (40, 3, "2016 Someecards Daily Desktop Calendar", "Someecards", "Calendars");
